### find all siswa
GET http://localhost:9000/api/siswa
Accept: application/json
### Create Siswa

### find by id siswa
GET http://localhost:9000/api/siswa/1
Accept: application/json

### create siswa
POST http://localhost:9000/api/siswa
Accept: application/json
Content-Type: application/json

{
    "name" :"Billy",
    "jurusan" :"IPA",
    "stambuk" :"2018"
}


### update siswa
PUT  http://localhost:9000/api/siswa/4
Accept: application/json
Content-Type: application/json

{
    "name" :"andi",
    "jurusan" :"IPS",
    "stambuk" :"2018"
}

###Delete Siswa
DELETE   http://localhost:9000/api/siswa/100
Accept: application/json


### find all guru
GET http://localhost:9000/api/guru
Accept: application/json

### create guru 
POST  http://localhost:9000/api/guru
Accept: application/json
Content-Type: application/json

{
    "id_guru" :"GR01",
    "name" :"Sir Billy",
    "birth_day":"2000-08-27T00:00:00Z",
    "married" :false,
    "no_hp" :"081263430600"
}

### update by id guru
PUT  http://localhost:9000/api/guru/GR01
Accept: application/json
Content-Type: application/json

{
    "name" :"Sir Billy Ginting",
    "birth_day":"2006-08-08T00:00:00Z",
    "married" :false,
    "no_hp" :"081263430600"
}

### find by id guru
GET http://localhost:9000/api/guru/GR02
Accept: application/json

### delete guru
DELETE  http://localhost:9000/api/guru/GR02
Accept: application/json
